language: ruby
cache: bundler
dist: trusty
rvm:
- 2.4.0
before_script:
- make install
script:
- make build
- make clean-deploy
env:
  global:
    secure: wsx2BZHPYI22y96tbS0u1So/OWL9A4z+dD/zARN2B5OELue4JC880wIkNUcUKCTzgUEPGQVHqoSj2TSiqbdasYOplt0rP7fsB4OKdBPMOyhYDsN5VjUxJQorKferogl+0oTWs15wJRf6jqsG7xKmKTnAFyR2PAWdYdJ9KgKZxnmRHm8ZM3RESivxsfmvPWd5qZD+MWc1AwahmvGTpqrWcbmyCbufdS7OSUsZ7Yw6imavIvnka4M3uHv7fiPT2AJZLPqSZP4iQPQEQDj7HolsK+OKL1jUEkJTlWdPZ1WEqh0wlNiDmdyFQSDbwm/1nUwAMA7ZHZpW1sM4rH2QeFkHdWVsz4TmMSwg0TYd6YQZ1KutzpH/LWF1Xdn5og9BjlqCqekjeZxsL4lvMw526+2FHL/Y5tsakzp5rtkEgOg/rsit5EvqvwOxAQMOXJNeIaJfMpW4j9ylE2gHyPB9SACWcBjW33rLfnv+Kjq52kdlsWgyhGx1nPfS7h+l2SiPddLM9ynNqtXQTnYdBIQfSbCypdMQ5Y34KndZSjY0TcJCSX6EhtkZVN4PCmtufAXRqFbO+JvpSNYa/0YUMB2JzwQ7bQ9pGQZfdkzyDRjglwnbxOKcM1etJ+u8qR7NUA9Ndyetya+2PHgsIZLdBpT+UVHTN+OosMjCNP5KnSltGUZwXw8=
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  target-branch: master
  fqdn: iamjohnnym.com
  on:
    branch: develop
