url: https://iamjohnnym.com
title: iamjohnnym
description: A technical journal to discuss ideas, opinions, frustrations, and tips. Covering programming, developing, operations, systems, and cloud technologies.
tagline: musings of an operator
sub_tagline: "<span class='command'>[iamjohnnym@musings ~] $</span> service operatord start <span class='comment'> # Begin musings of an operator</span><span class='blink'>_</span>"
show_downloads: false
google_analytics: UA-118583467-1
theme: jekyll-theme-hacker
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

github: [metadata]

repository: iamjohnnym/iamjohnnym.github.io

sass:
  load_paths:
    - _sass
    - node_modules
  style: compressed

exclude:
  - vendor
  - deploy.sh
  - node_modules
  - Makefile
  - Gemfile
  - Gemfile.lock
  - yarn.lock
  - packages.json
  - ruby
